# Workflow Name: Automatic Release

# Description:
# This GitHub Actions workflow is triggered when a tag is pushed. It builds the Cloney application 
# for multiple platforms, creates zip archives, generates checksums, and releases the artifacts 
# using the release-action GitHub action.

on:
  # Trigger when a tag is pushed.
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    # Give permissions to modify repository contents.
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository.
      - uses: actions/checkout@v3

      # Step 2: Setup Go.
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Step 3: Install goversioninfo to embed properties into the Windows executable.
      - name: Install goversioninfo
        run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.4.0

      # Step 4: Build the application for different platforms.
      - name: Build Application
        run: |
          goversioninfo -64
          GOOS=windows GOARCH=amd64 go build -o cloney-windows-amd64/cloney.exe
          rm -f resources.syso

          goversioninfo -arm
          GOOS=windows GOARCH=arm64 go build -o cloney-windows-arm64/cloney.exe
          rm -f resources.syso

          GOOS=linux GOARCH=amd64 go build -o cloney-linux-amd64/cloney
          GOOS=linux GOARCH=arm64 go build -o cloney-linux-arm64/cloney
          GOOS=darwin GOARCH=amd64 go build -o cloney-darwin-amd64/cloney
          GOOS=darwin GOARCH=arm64 go build -o cloney-darwin-arm64/cloney

      # Step 5: Zip the application for different platforms.
      - name: Zip Application
        run: |
          zip -r cloney-windows-amd64.zip cloney-windows-amd64
          zip -r cloney-windows-arm64.zip cloney-windows-arm64
          zip -r cloney-linux-amd64.zip cloney-linux-amd64
          zip -r cloney-linux-arm64.zip cloney-linux-arm64
          zip -r cloney-darwin-amd64.zip cloney-darwin-amd64
          zip -r cloney-darwin-arm64.zip cloney-darwin-arm64

      # Step 6: Generate checksums for the application.
      - name: Generate Checksums
        run: |
          sha256sum cloney-windows-amd64.zip > cloney-windows-amd64-checksum.sha256
          sha256sum cloney-windows-arm64.zip > cloney-windows-arm64-checksum.sha256
          sha256sum cloney-linux-amd64.zip > cloney-linux-amd64-checksum.sha256
          sha256sum cloney-linux-arm64.zip > cloney-linux-arm64-checksum.sha256
          sha256sum cloney-darwin-amd64.zip > cloney-darwin-amd64-checksum.sha256
          sha256sum cloney-darwin-arm64.zip > cloney-darwin-arm64-checksum.sha256

      # Step 7: Use the release-action GitHub action to create a release.
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cloney-*.zip,cloney-*.sha256"
        env:
          # Use a personal access token to create the release.
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
