name: Automatic Tag

# Trigger the workflow when a pull request is closed on the 'main' branch.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-22.04

    # Give permissions to modify repository contents.
    permissions:
      contents: write

    steps:
      # Check out the repository.
      - uses: actions/checkout@v3
        with:
          # Check out the specific commit associated with the closed pull request.
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          # Fetch all commit history for tags to work correctly.
          fetch-depth: "0"

      # Run auto-tag in dry-run mode to determine the next version.
      - name: Determine Next Version
        id: determine_next_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          # Do not prepend the 'v' prefix to the tag.
          WITH_V: false
          DRY_RUN: true

      # Get the output of the previous step.
      - name: Export Next Version
        run: export CLONEY_NEXT_VERSION=${{ steps.determine_next_version.outputs.new_tag }}

      # Edit the versioninfo.json file to update the version.
      - name: Edit versioninfo.json File

      # Edit the pkg/config/config.go file to update the version.
      - name: Edit pkg/config/config.go File

      # Edit the installation/install.sh file to update the version.
      - name: Edit installation/install.sh File

      # Use the GitHub Tag Action to create tags.
      - name: Bump Version and Push Tag.
        uses: anothrNick/github-tag-action@1.64.0
        env:
          # Use a personal access token to push the tag.
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Do not prepend the 'v' prefix to the tag.
          WITH_V: false
