name: Run Automated Tests

# Trigger when a PR is created against the main branch and when a commit is pushed to the main branch.
on:
  pull_request:
    types:
      - opened
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      # Check out the repository.
      - uses: actions/checkout@v3

      # Set up Go.
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Run the tests.
      - name: Run Tests
        run: go test ./... -v 

      #
      # Check if there are no errors when building the application.
      #

      # Install goversioninfo to embed properties into the Windows executable.
      - name: Check Install goversioninfo
        run: |
          go get github.com/josephspurrier/goversioninfo@v1.4.0
          go install github.com/josephspurrier/goversioninfo

      # Build the application.
      - name: Build Application
        run: |
          goversioninfo -64
          GOOS=windows GOARCH=amd64 go build -o cloney-windows-amd64/cloney.exe
          rm -f resources.syso

      # Zip the application.
      - name: Check Zip Application
        run: zip -r cloney-windows-amd64.zip cloney-windows-amd64

      # Generate checksum for the application.
      - name: Check Generate Checksums
        run: sha256sum cloney-windows-amd64.zip > cloney-windows-amd64-checksum.sha256

      # Check if the checksum matches.
      - name: Check Checksum Matches
        run: sha256sum -c cloney-windows-amd64-checksum.sha256
