# Workflow Name: Run Automated Tests

# Description:
# This GitHub Actions workflow is triggered when a pull request is created against the main branch 
# or when a commit is pushed to the main branch. It runs automated tests for the Go application, 
# and validates the build steps (e.g., building the Windows executable, creating a zip archive, 
# and generating checksums) without actually releasing the application.

on:
  # Trigger when a PR is created against the main branch.
  pull_request:
    types:
      - opened
    branches:
      - main
  # Trigger when a commit is pushed to the main branch.
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Check out the repository.
      - uses: actions/checkout@v3

      # Step 2: Set up Go.
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Step 3: Run the tests.
      - name: Run Tests
        run: go test ./... -v 

      #
      # Validate build steps (not actual release).
      #

      # Step 4: Install goversioninfo to embed properties into the Windows executable.
      - name: Install goversioninfo
        run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.4.0

      # Step 5: Validate building the application for Windows.
      - name: Validate Build for Windows
        run: |
          goversioninfo -64
          GOOS=windows GOARCH=amd64 go build -o cloney-windows-amd64/cloney.exe
          rm -f resources.syso

      # Step 6: Validate creating a zip archive.
      - name: Validate Zip Application
        run: zip -r cloney-windows-amd64.zip cloney-windows-amd64

      # Step 7: Validate generating checksum for the application.
      - name: Validate Generate Checksums
        run: sha256sum cloney-windows-amd64.zip > cloney-windows-amd64-checksum.sha256

      # Step 8: Validate checksum matches.
      - name: Validate Checksum Matches
        run: sha256sum -c cloney-windows-amd64-checksum.sha256
